"""ИНН должника из выгрузки.

Без него банкротство, статус ИП и арбитраж не проверяются вовсе: эти источники
ищут только по ИНН. В выгрузке из 1С он обычно есть, а импорт до сих пор его
молча выбрасывал — колонки просто не существовало.

Оригинально: inn_from_export

Revision ID: 5d86bbd033c1
Revises: 0006
Create Date: 2026-09-05 17:36:32.810362
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debtors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inn', sa.String(length=12), nullable=True))
        batch_op.create_index(batch_op.f('ix_debtors_inn'), ['inn'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debtors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debtors_inn'))
        batch_op.drop_column('inn')

    # ### end Alembic commands ###
